# .streamlit/config.toml

[server]
headless = true
port = $PORT  # Remove as aspas ao redor de $PORT
enableCORS = false

[theme]
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
